# https://competitive-verifier.github.io/competitive-verifier/
remote_theme: just-the-docs/just-the-docs
title: gwen
description: Competitive Programming Library (C++23)
url: ""
markdown: kramdown
kramdown:
  math_engine: mathjax
