# https://competitive-verifier.github.io/competitive-verifier/
theme: jekyll-theme-cayman
title: gwen
description: Competitive Programming Library (C++20)
url: ""
plugins:
  - jekyll-mathjax
markdown: kramdown
kramdown:
  math_engine: mathjax
