// Auto-generated by scripts/manage_problems.py. DO NOT EDIT!
#include <gtest/gtest.h>
#include "runner_utils.hpp"

const std::string project_root = PROJECT_ROOT;
const std::string build_dir = BUILD_DIR;

void run_test_case(const std::string& problem_name, const std::string& case_name) {
    std::string exe_path = build_dir + "/test/problem_" + problem_name;
    std::string input_path = project_root + "/test/problems/" + problem_name + "/cases/" + case_name + ".in";
    std::string expected_path = project_root + "/test/problems/" + problem_name + "/cases/" + case_name + ".out";

    std::string actual = test_utils::run_problem_exe(exe_path, input_path);
    std::string expected = test_utils::read_file(expected_path);

    EXPECT_EQ(test_utils::normalize_output(actual), test_utils::normalize_output(expected))
        << "Failed on problem: " << problem_name << ", case: " << case_name;
}

// factorize tests
TEST(ProblemIntegrationTest, Factorize_01) { run_test_case("factorize", "01"); }
TEST(ProblemIntegrationTest, Factorize_02) { run_test_case("factorize", "02"); }
TEST(ProblemIntegrationTest, Factorize_03) { run_test_case("factorize", "03"); }

// lca tests
TEST(ProblemIntegrationTest, Lca_01) { run_test_case("lca", "01"); }
TEST(ProblemIntegrationTest, Lca_02) { run_test_case("lca", "02"); }
