#!/usr/bin/env python3
import argparse
import os
import sys
import yaml
import subprocess
import urllib.request

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
PROBLEMS_DIR = os.path.join(ROOT_DIR, 'test', 'problems')
TEST_RUNNER_DIR = os.path.join(ROOT_DIR, 'test', 'problem_runner')
INCLUDE_DIR = os.path.join(ROOT_DIR, 'test', 'include')
CMAKE_FILE = os.path.join(ROOT_DIR, 'test', 'CMakeLists.txt')
TEST_CPP_FILE = os.path.join(TEST_RUNNER_DIR, 'test_problems.cpp')
TESTLIB_URL = "https://raw.githubusercontent.com/MikeMirzayanov/testlib/master/testlib.h"

def get_problems():
    problems = []
    if not os.path.exists(PROBLEMS_DIR):
        return problems
    for d in sorted(os.listdir(PROBLEMS_DIR)):
        dpath = os.path.join(PROBLEMS_DIR, d)
        if os.path.isdir(dpath) and os.path.exists(os.path.join(dpath, 'solution.cpp')):
            problems.append(d)
    return problems

def get_cases(problem_id):
    cases_dir = os.path.join(PROBLEMS_DIR, problem_id, 'cases')
    cases = set()
    if os.path.exists(cases_dir):
        for f in os.listdir(cases_dir):
            if f.endswith('.in'):
                cases.add(f[:-3])
    return sorted(list(cases))

def read_meta(problem_id):
    meta_path = os.path.join(PROBLEMS_DIR, problem_id, 'meta.yaml')
    if not os.path.exists(meta_path):
        return {}
    with open(meta_path, 'r', encoding='utf-8') as f:
        try:
            return yaml.safe_load(f) or {}
        except Exception as e:
            print(f"Error parsing {meta_path}: {e}")
            return {}

def generate_problem_md(problem_id, meta, cases):
    md_path = os.path.join(PROBLEMS_DIR, problem_id, 'problem.md')
    title = meta.get('title', problem_id)
    tags = meta.get('tags', [])
    timeout = meta.get('timeout_sec', 2.0)
    
    lines = []
    lines.append(f"# {title}")
    lines.append("")
    if tags:
        badges = " ".join([f"`{tag}`" for tag in tags])
        lines.append(f"**Tags:** {badges}")
        lines.append("")
    lines.append(f"**Time Limit:** {timeout} sec")
    lines.append("")
    
    if 'description' in meta:
        lines.append("## 問題文")
        lines.append(meta['description'].strip())
        lines.append("")
    
    if 'constraints' in meta:
        lines.append("## 制約")
        lines.append(meta['constraints'].strip())
        lines.append("")
        
    if 'input_format' in meta:
        lines.append("## 入力")
        lines.append("```text")
        lines.append(meta['input_format'].strip())
        lines.append("```")
        lines.append("")
        
    if 'output_format' in meta:
        lines.append("## 出力")
        lines.append("```text")
        lines.append(meta['output_format'].strip())
        lines.append("```")
        lines.append("")
        
    samples = meta.get('samples', [])
    if not samples and cases:
        samples = [cases[0]] # Default to first case if exists
        
    for i, sample_case in enumerate(samples, 1):
        in_path = os.path.join(PROBLEMS_DIR, problem_id, 'cases', f'{sample_case}.in')
        out_path = os.path.join(PROBLEMS_DIR, problem_id, 'cases', f'{sample_case}.out')
        
        lines.append(f"## サンプル {i}")
        if os.path.exists(in_path):
            with open(in_path, 'r', encoding='utf-8') as f:
                lines.append("### 入力例")
                lines.append("```text")
                lines.append(f.read().strip())
                lines.append("```")
        if os.path.exists(out_path):
            with open(out_path, 'r', encoding='utf-8') as f:
                lines.append("### 出力例")
                lines.append("```text")
                lines.append(f.read().strip())
                lines.append("```")
        lines.append("")
        
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    print(f"Generated {md_path}")

def generate_test_cpp(problems):
    lines = [
        "// Auto-generated by scripts/manage_problems.py. DO NOT EDIT!",
        "#include <gtest/gtest.h>",
        '#include "runner_utils.hpp"',
        "",
        "const std::string project_root = PROJECT_ROOT;",
        "const std::string build_dir = BUILD_DIR;",
        "",
        "void run_test_case(const std::string& problem_name, const std::string& case_name) {",
        '    std::string exe_path = build_dir + "/test/problem_" + problem_name;',
        '    std::string input_path = project_root + "/test/problems/" + problem_name + "/cases/" + case_name + ".in";',
        '    std::string expected_path = project_root + "/test/problems/" + problem_name + "/cases/" + case_name + ".out";',
        "",
        "    std::string actual = test_utils::run_problem_exe(exe_path, input_path);",
        "    std::string expected = test_utils::read_file(expected_path);",
        "",
        '    EXPECT_EQ(test_utils::normalize_output(actual), test_utils::normalize_output(expected))',
        '        << "Failed on problem: " << problem_name << ", case: " << case_name;',
        "}",
        ""
    ]
    
    for prob in problems:
        cases = get_cases(prob)
        if not cases:
            continue
        lines.append(f"// {prob} tests")
        prob_camel = "".join([w.capitalize() for w in prob.split('_')])
        for case in cases:
            case_clean = case.replace('-', '_').replace('.', '_')
            lines.append(f'TEST(ProblemIntegrationTest, {prob_camel}_{case_clean}) {{ run_test_case("{prob}", "{case}"); }}')
        lines.append("")
        
    with open(TEST_CPP_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    print(f"Generated {TEST_CPP_FILE}")

def update_cmake(problems):
    if not os.path.exists(CMAKE_FILE):
        print(f"Error: {CMAKE_FILE} not found!")
        return
        
    with open(CMAKE_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
        
    start_marker = "# <<< GENERATED SOLUTIONS START >>>"
    end_marker = "# <<< GENERATED SOLUTIONS END >>>"
    
    start_idx = content.find(start_marker)
    end_idx = content.find(end_marker)
    
    if start_idx == -1 or end_idx == -1:
        print(f"Markers not found in {CMAKE_FILE}. Please add them.")
        return
        
    gen_lines = []
    gen_lines.append(start_marker)
    for prob in problems:
        gen_lines.append(f"add_executable(problem_{prob} problems/{prob}/solution.cpp)")
        gen_lines.append(f"target_link_libraries(problem_{prob} PRIVATE gwen)")
        gen_lines.append("")
    gen_lines.append(end_marker)
    
    new_content = content[:start_idx] + "\n".join(gen_lines) + content[end_idx + len(end_marker):]
    with open(CMAKE_FILE, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Updated {CMAKE_FILE}")

def download_testlib():
    os.makedirs(INCLUDE_DIR, exist_ok=True)
    testlib_path = os.path.join(INCLUDE_DIR, 'testlib.h')
    if not os.path.exists(testlib_path):
        print(f"Downloading testlib.h to {testlib_path}...")
        try:
            urllib.request.urlretrieve(TESTLIB_URL, testlib_path)
            print("Download complete.")
        except Exception as e:
            print(f"Failed to download testlib.h: {e}")
            sys.exit(1)
    return testlib_path

def cmd_generate_all():
    problems = get_problems()
    print(f"Found {len(problems)} problems.")
    for prob in problems:
        meta = read_meta(prob)
        cases = get_cases(prob)
        generate_problem_md(prob, meta, cases)
    generate_test_cpp(problems)
    update_cmake(problems)

def cmd_validate_inputs():
    testlib_path = download_testlib()
    problems = get_problems()
    build_dir = os.path.join(ROOT_DIR, '.build', 'validator')
    os.makedirs(build_dir, exist_ok=True)
    
    success = True
    for prob in problems:
        val_cpp = os.path.join(PROBLEMS_DIR, prob, 'validator.cpp')
        print(val_cpp)
        if not os.path.exists(val_cpp):
            continue
            
        print(f"Validating inputs for {prob}...")
        val_exe = os.path.join(build_dir, f"val_{prob}")
        compile_cmd = ["g++", "-std=c++20", "-O2", f"-I{INCLUDE_DIR}", val_cpp, "-o", val_exe]
        res = subprocess.run(compile_cmd, capture_output=True, text=True)
        if res.returncode != 0:
            print(f"Compilation failed for {prob}/validator.cpp:\n{res.stderr}")
            success = False
            continue
            
        cases = get_cases(prob)
        for case in cases:
            in_path = os.path.join(PROBLEMS_DIR, prob, 'cases', f'{case}.in')
            with open(in_path, 'rb') as f:
                res = subprocess.run([val_exe], stdin=f, capture_output=True, text=True)
            if res.returncode != 0:
                print(f"  [FAIL] {case}.in: {res.stderr.strip()}")
                success = False
            else:
                print(f"  [OK]   {case}.in")
                
    if not success:
        sys.exit(1)

def cmd_generate_outputs():
    problems = get_problems()
    build_dir = os.path.join(ROOT_DIR, '.build', 'naive')
    os.makedirs(build_dir, exist_ok=True)
    
    for prob in problems:
        naive_cpp = os.path.join(PROBLEMS_DIR, prob, 'naive.cpp')
        if not os.path.exists(naive_cpp):
            print(f"[{prob}] naive.cpp not found. Skipping output generation to avoid self-validation with solution.cpp.")
            continue
            
        print(f"[{prob}] Compiling naive.cpp...")
        naive_exe = os.path.join(build_dir, f"naive_{prob}")
        if os.name == 'nt':
            naive_exe += '.exe'
            
        compile_cmd = ["g++", "-std=c++20", "-O2", f"-I{INCLUDE_DIR}", naive_cpp, "-o", naive_exe]
        res = subprocess.run(compile_cmd, capture_output=True, text=True)
        if res.returncode != 0:
            print(f"Compilation failed for {prob}/naive.cpp:{res.stderr}")
            continue
            
        cases = get_cases(prob)
        for case in cases:
            in_path = os.path.join(PROBLEMS_DIR, prob, 'cases', f'{case}.in')
            out_path = os.path.join(PROBLEMS_DIR, prob, 'cases', f'{case}.out')
            
            print(f"  Generating output for {case}...")
            with open(in_path, 'rb') as fin, open(out_path, 'wb') as fout:
                res = subprocess.run([naive_exe], stdin=fin, stdout=fout)
                if res.returncode != 0:
                    print(f"    [ERROR] naive.cpp crashed on {case}.in")

def main():
    parser = argparse.ArgumentParser(description="Manage Gwen problem integration tests")
    parser.add_argument('command', choices=['generate-all', 'validate-inputs', 'generate-outputs'])
    args = parser.parse_args()
    
    if args.command == 'generate-all':
        cmd_generate_all()
    elif args.command == 'validate-inputs':
        cmd_validate_inputs()
    elif args.command == 'generate-outputs':
        cmd_generate_outputs()

if __name__ == '__main__':
    main()
